POST http://localhost:8800/api/markers
Content-Type: application/json

{
    "username": "john",
    "title": "Eiffel tower",
    "description": "It was an amazing place",
    "rating": 5,
    "latitude": 43,
    "longitude": 10
}

###

GET http://localhost:8800/api/markers
Content-Type: application/json

###
POST http://localhost:8800/api/users/register
Content-Type: application/json

{
    "username": "kostas",
    "email": "kostas@gmail.com",
    "password": "123456"
}

###
GET http://localhost:8800/api/users/login
Content-Type: application/json

{
    "username": "kostas",
    "password": "123456"
}